version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6
    container_name: recipe-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: recipe-book
    volumes:
      - mongodb_data:/data/db
    networks:
      - recipe-network
    ports:
      - "27017:27017"

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: recipe-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/recipe-book
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      CLIENT_URL: ${CLIENT_URL:-http://localhost}
      PORT: 5000
    depends_on:
      - mongodb
    networks:
      - recipe-network
    ports:
      - "5000:5000"

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        REACT_APP_API_URL: ${API_URL:-/api}
    container_name: recipe-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - recipe-network
    ports:
      - "80:80"
      - "443:443"

networks:
  recipe-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
