services:
  # Backend API Service
  - type: web
    name: recipe-book-api
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://recipe-book-frontend-8f1r.onrender.com
      - key: PORT
        value: 5000

  # Frontend Static Site  
  - type: web
    name: recipe-book-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    envVars:
      - key: REACT_APP_API_URL
        value: https://recipe-book-api-syqv.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html